version: "3.8"
services:
  app:
    image: ghcr.io/pwojszko/ani-me:ani-me-client
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
