import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BigNavbar from "@/app/BigNavbar";
import SmallBottomNavbar from "./SmallBottomNavbar";
import "./globals.css";
import SmallTopNavbar from "./SmallTopNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen">
        <div className="flex flex-col md:flex-row flex-1">
          <div className="md:hidden sticky top-0 z-20">
            <SmallTopNavbar />
          </div>

          <div className="hidden md:block">
            <BigNavbar />
          </div>

          <main className="relative pb-10 flex-1">{children}</main>

          <div className="md:hidden sticky bottom-0 z-20">
            <SmallBottomNavbar />
          </div>
        </div>
      </body>
    </html>
  );
}
