import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BigNavbar from "@/components/Navbar/BigNavbar";
import SmallBottomNavbar from "../components/Navbar/SmallBottomNavbar";
import "./globals.css";
import SmallTopNavbar from "../components/Navbar/SmallTopNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen w-full place-content-center place-items-center">
        {children}
      </body>
    </html>
  );
}
